### ISSUE TITLE
如何用机器人模拟两个游戏玩家在线聊天呢？可以给个demo吗？

### ISSUE THREAD

**Issue by netgb** [kingston-csj/jforgame#11]
还有业务逻辑这里具体怎么用，比如这个方法GameServer.gameLogicInit，可以提供demo模拟一下使用的情况吗？

**Comment by kingston-csj** [comment]
游戏业务很多啊，诸如场景地图的初始化，活动啊，排行榜各种业务的初始化。都写在这里。

**Comment by kingston-csj** [comment]
周末有空，可以提供下聊天机器人的示例代码

**Comment by netgb** [comment]
> 游戏业务很多啊，诸如场景地图的初始化，活动啊，排行榜各种业务的初始化。都写在这里。

主要是不知道如何合理的使用，你说的功能能用伪代码大概模拟一下吗？没思路。。

**Comment by netgb** [comment]
> 周末有空，可以提供下聊天机器人的示例代码

昨晚看了那个im项目是不是游戏里面的聊天和im项目一样的？

**Comment by kingston-csj** [comment]
肯定不一样啊，游戏里的聊天功能没那么复杂。

**Comment by netgb** [comment]
期待使用案例，很想多了解一些游戏服务端开发方面的内容，希望能抽空来提供多一些项目使用方面的演示代码啦

**Comment by kingston-csj** [comment]
> 期待使用案例，很想多了解一些游戏服务端开发方面的内容，希望能抽空来提供多一些项目使用方面的演示代码啦

提交了一版简单的聊天demo。重新导入user.sql。
先启动ServerStartup，再启动RobotStartup。

**Comment by netgb** [comment]
[12 18:33:27,893 INFO ] [main] server.ServerVersion - 加载服务版本号成功, bigVersion=1, smallVersion=0
[12 18:33:28,299 ERROR] [main] server.ServerStartup - server start failed
java.lang.RuntimeException: message meta [101001] duplicate！！
	at com.kingston.jforgame.socket.message.MessageFactory.initMeesagePool(MessageFactory.java:31)
	at com.kingston.jforgame.server.GameServer.frameworkInit(GameServer.java:65)
	at com.kingston.jforgame.server.GameServer.start(GameServer.java:48)
	at com.kingston.jforgame.server.ServerStartup.main(ServerStartup.java:21)

Process finished with exit code -1
服务端直接报错了

**Comment by netgb** [comment]
[12 20:00:09,944 INFO ] [main] net.SocketServer - socket server start at port:9527,正在监听客户端的连接...
[12 20:00:10,100 ERROR] [main] server.GameServer - 游戏服务启动，耗时[1790]毫秒
/172.22.105.177:43105
[12 20:00:24,579 INFO ] [NioProcessor-2] filter.MessageTraceFilter - <<<<<<<<<<[1]ReqCreateNewPlayerMessage={"name":"robot_1000"}
received message -->{"name":"robot_1000"}
[12 20:00:25,199 ERROR] [message-task-handler-thread-1] task.MessageTask - message task execute failed 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.kingston.jforgame.socket.task.MessageTask.action(MessageTask.java:45)
	at com.kingston.jforgame.socket.task.TaskHandlerContext$TaskWorker.run(TaskHandlerContext.java:81)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.kingston.jforgame.server.game.player.PlayerManager.createNewPlayer(PlayerManager.java:92)
	at com.kingston.jforgame.server.game.player.facade.PlayerController.reqCreateNewPlayer(PlayerController.java:15)
	... 7 more

RobotStartup启动后服务端还是有报错出现

**Comment by kingston-csj** [comment]
> [12 20:00:09,944 INFO ] [main] net.SocketServer - socket server start at port:9527,正在监听客户端的连接...
> [12 20:00:10,100 ERROR] [main] server.GameServer - 游戏服务启动，耗时[1790]毫秒
> /172.22.105.177:43105
> [12 20:00:24,579 INFO ] [NioProcessor-2] filter.MessageTraceFilter - <<<<<<<<<<[1]ReqCreateNewPlayerMessage={"name":"robot_1000"}
> received message -->{"name":"robot_1000"}
> [12 20:00:25,199 ERROR] [message-task-handler-thread-1] task.MessageTask - message task execute failed
> java.lang.reflect.InvocationTargetException
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.kingston.jforgame.socket.task.MessageTask.action(MessageTask.java:45)
> at com.kingston.jforgame.socket.task.TaskHandlerContext$TaskWorker.run(TaskHandlerContext.java:81)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException
> at com.kingston.jforgame.server.game.player.PlayerManager.createNewPlayer(PlayerManager.java:92)
> at com.kingston.jforgame.server.game.player.facade.PlayerController.reqCreateNewPlayer(PlayerController.java:15)
> ... 7 more
> 
> RobotStartup启动后服务端还是有报错出现

更新下最新代码，完善了登录流程
