### ISSUE TITLE
at com.kingston.jforgame.server.game.core.SchedulerManager.scheduleAtFixedRate(SchedulerManager.java:41)

### ISSUE THREAD

**Issue by netgb** [kingston-csj/jforgame#12]
java.lang.NullPointerException
	at com.kingston.jforgame.server.game.core.SchedulerManager.scheduleAtFixedRate(SchedulerManager.java:41)
	at com.kingston.jforgame.server.robot.Robot.runAi(Robot.java:73)
	at com.kingston.jforgame.server.robot.handler.CreatePlayerHandler.onMessageReceive(CreatePlayerHandler.java:13)
	at com.kingston.jforgame.server.robot.RobotSession.receiveMessage(RobotSession.java:39)
	at com.kingston.jforgame.server.robot.Robot$ClientHandler.messageReceived(Robot.java:103)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
我这里本机测试robot的demo不正常，
1、(SchedulerManager.java:41)里的貌似不能被初始化service对象是null的，
2、运行demo数据库会重复创建玩家
不过虽然爆异常，服务端可以看到客户端发过来的消息了 @kingston-csj

**Comment by kingston-csj** [comment]
这阵子很忙，有空再休下bug

**Comment by kingston-csj** [comment]
重复创建玩家的bug修复了。另外一个报空的异常重现不了
